- name: "Adicionar chave GPG oficial do Docker"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: "Adicionar repositório do Docker"
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
- name: "Instalar Docker Engine"
  ansible.builtin.apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: present
    update_cache: yes
- name: "Instalar pip3 e dependências de Python"
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
    state: present
    update_cache: yes
  register: apt_status_docker
  until: apt_status_docker is succeeded
  retries: 5
  delay: 10  
- name: "Instalar o módulo Docker para Ansible via pip"
  ansible.builtin.pip:
    name: docker
    executable: pip3
- name: "Atualizar SDK Docker via pip3"
  pip:
    name: docker
    state: latest
    executable: pip3

- name: "Garantir que o serviço Docker esteja iniciado"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
